### ISSUE TITLE
[feature] Support submodule of remote theme

### ISSUE THREAD

**Issue by Freed-Wu** [benbalter/jekyll-remote-theme#99]
### Describe the solution you'd like

A `username/reponame` may contain a git submodule, like <https://github.com/allejo/jekyll-toc>.

```yaml
remote_theme:
  url: username/reponame
  submodule: true
```

### Describe alternatives you've considered

```yaml
remote_theme:
  url: username/reponame
  option: --recurse-submodules
```
